version: '2'
services:
  cdn-service-provider-api:
    build: service_provider_example/
    image: cdn-service-provider-api:latest
    container_name: cdn-service-provider-api
    ports:
     - "8080:80"
     - "8443:443"

  swagger-ui-cdn:
    image: swaggerapi/swagger-ui:latest
    container_name: swagger-ui-cdn
    ports:
     - "8082:8080"
    environment:
      - SWAGGER_JSON=/app/resources/swagger.yaml
    volumes:
      - ./service_provider_example:/app