# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  branch = "master"
  name = "github.com/dikhan/http_goclient"

[[constraint]]
  branch = "master"
  name = "github.com/go-openapi/loads"

[[constraint]]
  branch = "master"
  name = "github.com/go-openapi/spec"

[[constraint]]
  branch = "master"
  name = "github.com/goadesign/goa"

# Pinning 'hashicorp/terraform' and 'hashicorp/go-plugin' to specific versions to avoid compatibility issues
# as described here: https://github.com/hashicorp/terraform/issues/15756
[[constraint]]
  name = "github.com/hashicorp/terraform"
#  branch = "master"
  version = "v0.11.8"

[[override]]
  name = "github.com/hashicorp/go-plugin"
#  branch = "master"
  revision = "e8d22c780116115ae5624720c9af0c97afe4f551"

[[constraint]]
  name = "github.com/smartystreets/goconvey"
  version = "1.6.3"

#[[override]]
#    name = "github.com/satori/go.uuid"
#    revision = "master"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"

[[constraint]]
  name = "github.com/asaskevich/govalidator"
  version = "8.0.0"

[[constraint]]
#  branch = "master"
  name = "github.com/mitchellh/go-homedir"
  revision = "b8bc1bf767474819792c23f32d8286a45736f1c6"
